### ISSUE TITLE
metrics issue when adding new fields

### ISSUE THREAD

**Issue by akeshthemesh** [311labs/restit#1]
when you use metrics the db version, it does not take new fields after it updates the first time.

**Comment by istarnes** [comment]
So I understand correctly... are you saying that you call models.metric with a slug with one set of keys like ["key1", "key2"]
then later you add "key3" so your keys are ["key1", "key2", "key3"]?   This should work fine, do you have example code?

**Comment by akeshthemesh** [comment]
Yes adding new keys.   When i call get_totals the new keys are not in the
response of day, month, year totals.

To reproduce...
from metrics import models as metrics
# call the first time
metrics.metric("my_random_slug", ["key1", "key2"], {"key1":1, "key2":5})
# now call again
metrics.metric("my_random_slug", ["key1", "key2", "key3"], {"key1":1,
"key2":10, "key3":1})
# next call get_totals
metrics.get_totals("my_random_slug",  ["key1", "key2", "key3"], {"key1":1,
"key2":1, "key3":1}, "daily")
# you will see "key3" is not returned!
{"key1":2, "key2":15}

**Comment by istarnes** [comment]
This should resolved now, it will check if keys are out of sync and resync keys to the model.
